apiVersion: apps/v1
kind: Deployment
metadata:
  name: advertise-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advertise-service
  template:
    metadata:
      labels:
        app: advertise-service
    spec:
      containers:
        - name: advertise-service
          image: midtermexam.azurecr.io/advertise-service:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: advertise-service
spec:
  selector:
    app: advertise-service
  ports:
    - port: 80
