apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
        - name: history
          image: midtermexam.azurecr.io/history:latest
          ports:
            - containerPort: 80
          environment:
            - name: DBHOST
              value: mongodb://db:27017
            - name: DBNAME
              value: history
            - name: RABBIT
              value: amqp://test:test@rabbit:5672
            - name: NODE_ENV
              value: development
---
apiVersion: v1
kind: Service
metadata:
  name: history-service
spec:
  selector:
    app: history
  ports:
    - port: 80
