apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
        - name: rabbit
          image: midtermexam.azurecr.io/rabbit:latest
          ports:
            - containerPort: 5672
            - containerPort: 15672
          environment:
            - name: RABBITMQ_DEFAULT_USER
              value: test
            - name: RABBITMQ_DEFAULT_PASS
              value: test
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  selector:
    app: rabbit
  ports:
    - port: 5672
    - port: 15672
