apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers:
        - name: video-streaming
          image: midtermexam.azurecr.io/video-streaming:latest
          ports:
            - containerPort: 80
          environment:
            - name: RABBIT
              value: amqp://test:test@rabbit:5672
            - name: NODE_ENV
              value: development
---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming-service
spec:
  selector:
    app: video-streaming
  ports:
    - port: 80
