apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-storage
  template:
    metadata:
      labels:
        app: video-storage
    spec:
      containers:
        - name: video-storage
          image: midtermexam.azurecr.io/video-storage:latest
          ports:
            - containerPort: 80
          environment:
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: video-storage-service
spec:
  selector:
    app: video-storage
  ports:
    - port: 80
